name: Python API CI/CD to Azure

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and push Docker image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.REGISTRY_LOGIN_SERVER }}/python-api:${{ github.sha }}"
          echo "Building Docker image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-api:${{ github.sha }}
